### ISSUE TITLE
Getting streamURL

### ISSUE THREAD

**Issue by hugoerg56** [OpenKickflip/openkickflip-ios-sdk#4]
Trying on 

```
- (void) recorderDidStartRecording:(KFRecorder *)recorder error:(NSError *)error {
  recorder.stream.streamURL is just empty
```

and waiting for:
```
- (void) recorder:(KFRecorder *)recorder streamReadyAtURL:(NSURL *)url {
   this url, "never happens" some times returns me a url but that after  ended the video
}
```

how can get the stream url just doing:

```
    recorder = KFRecorder.alloc.init
    recorder.s3Configuration = $s3Config
    recorder.startRecording
```

**Comment by hugoerg56** [comment]
any idea @nicholas @duanmua

**Comment by duanmua** [comment]
@hugoerg56 I've swapped out the server side with my own code, which sets the streamURL on the stream on its creation, so I'm not sure what Kickflip's built in behavior is for when streamURL is set

However, why access the streamURL within the broadcast? For sharing?

**Comment by hugoerg56** [comment]
Yes Alan is for sharing, i need to share live. You have a repo to fork?

**Comment by hugoerg56** [comment]
@nicholas any idea of how obtain the STREAMURL when you start recording?, for now you can only get at the end of the recording.

**Comment by nicholas** [comment]
I should be able to check it out this weekend. It's normal for there to be a delay (5 to 10 seconds) due to the HLS manifest having to build up, but having to wait till the end is definitely a bug.

**Comment by hugoerg56** [comment]
yes I try 1 and 2 minutes videos and nothing, streamReadyAtURL:(NSURL *)url  is called only after stop the stram. And thanks!

**Comment by nicholas** [comment]
I should note that the way I use Kickflip is probably different than most. I had a project where we did a completely custom player .. so it's not surprising to see some issues crop up for people using the Kickflip player. The maintainer of Kickflip is working with me on merging my changes and one of the things I'll be looking at is making sure everything functions as expected with that player. Stay tuned.

**Comment by nicholas** [comment]
Gave this a look and am having trouble reproducing. The custom player I mentioned is irrelevant since it's only used after recordings.

I wonder if it's related to device? I tested with: Xcode 7.2, Cocoapods 0.38.2, iPhone 6s, iOS 9.1/9.2.

After some attempts to remove the API dependencies from the example project, I think it makes more sense to have a new barebones project that doesn't try to list videos you took. Just puts them on S3 and the rest is up to you. If you want to provide me with something like that so we can be on even ground to reproduce the issue, cool. I'll get to it when I have the time otherwise (maybe in the upcoming week)

Side note, looks like Chris recently updated FFmpeg to 2.8.3 (was 2.2) (https://github.com/chrisballinger/ffmpeg-ios-static-libs/commits/master). My code worked with both, but not without issue on 2.8.3. Looks like the manifest chunk durations got messed up a bit. Also, with 2.8.3, I had to manually disable librtmp references in KFHLSWriter.m. Still, pseudo-working and definitely was getting back a url via the streamReadyAtURL callback (Around 5 seconds in). I suggest sticking with 2.2  until that stuff is figured out.

Sorry this isn't of more help .. going to need some more time (holidays are hectic) to get some code together we can all run to test against.

**Comment by hugoerg56** [comment]
hi @nicholas I try againg in another internet provider and now i get the url about 5 seconds later, the only problem is that it only shows the end of the stream, if I record for 30 seconds it only shows the last few seconds of the stream on the play back.

**Comment by hugoerg56** [comment]
forget it @nicholas everything working fine! thanks!
